/* This file was autogenerated. All changes will be undone. */

#include <protocol.h>

const uint8_t msg_data_offset = 12;

void unpack_proto_msg_t(
   proto_msg_t* msg,
   proto_msg_buf_t* buf)
{
   uint8_t* unpack_offset = msg->data+msg_data_offset;
   switch(msg->header.message_type)
   {
   case Proto_UGV_Joystick:
      unpack_UGV_joystick(unpack_offset, &buf->UGV_joystick);
      break;
   case Proto_UGV_Battery_Status:
      unpack_UGV_battery_status(unpack_offset, &buf->UGV_battery_status);
      break;
   default:
      break;
   }
}

char* proto_typestr(proto_msg_type_t msg_type)
{
   if(msg_type == Proto_UGV_Joystick)
   {
      return "UGV Joystick";
   }
   if(msg_type == Proto_UGV_Battery_Status)
   {
      return "UGV Battery Status";
   }
   return 0;
}