/* This file was autogenerated. All changes will be undone. */

/* Message: UGV_Battery_Status, ID: 5001*/

#ifndef _UGV_BATTERY_STATUS_H_
#define _UGV_BATTERY_STATUS_H_

#include <marshal.h>
#include <message.h>

typedef struct {
   float64_t timestamp;
   float64_t 3_3V_voltage;
   float64_t 5V_voltage;
   float64_t 12V_voltage;
   float64_t 3_3V_current;
   float64_t 5V_current;
   float64_t 12V_current;
} UGV_battery_status_t;

msg_offset pack_UGV_battery_status(
   UGV_battery_status_t* UGV_battery_status,
   msg_offset offset);

msg_offset unpack_UGV_battery_status(
   msg_offset offset,
   UGV_battery_status_t* out_ptr);

void encode_UGV_battery_status(
   uint8_t src_id,
   uint8_t dest_id,
   uint8_t msg_ttl,
   uint8_t seq_number,
   UGV_battery_status_t* tx_msg,
   proto_msg_t* msg);

#endif