/* This file was autogenerated. All changes will be undone. */

#ifndef _MSG_H_
#define _MSG_H_

#include <stdint.h>
#include <stdio.h>
#include <marshal.h>

typedef struct {
   uint8_t node_src_id;
   uint8_t node_dest_id;
   uint8_t sequence_number;
   uint8_t message_ttl;
   uint16_t message_type;
   uint16_t message_length;
} proto_header_t;

typedef int8_t checksum_t;

typedef enum proto_direction {
   Proto_Out = 0,
   Proto_In = 1
} proto_direction_t;

typedef struct {
   proto_header_t header;
   proto_direction_t direction;
   uint8_t link_id;
   uint8_t data[540];
   checksum_t checksum;
} proto_msg_t;

msg_offset pack_sync(msg_offset offset);

msg_offset pack_checksum(
   const msg_offset start,
   const msg_offset end);

msg_offset pack_header(
   proto_header_t* header,
   msg_offset offset);

msg_offset unpack_header(
   msg_offset offset,
   proto_header_t* out_ptr);

typedef enum {
   Proto_UGV_Joystick = 5000,
   Proto_UGV_Battery_Status = 5001,
} proto_msg_type_t;

#endif