/* This file was autogenerated. All changes will be undone. */

#ifndef _PROTOCOL_H_
#define _PROTOCOL_H_

#include <message.h>
#include <message/UGVJoystick.h>
#include <message/UGVBatteryStatus.h>

typedef union {
   UGV_joystick_t UGV_joystick;
   UGV_battery_status_t UGV_battery_status;
} proto_msg_buf_t;

void unpack_proto_msg_t(
   proto_msg_t* msg,
   proto_msg_buf_t* buf);

char* proto_typestr(proto_msg_type_t msg_type);

#endif